# Generated by Django 5.1.6 on 2025-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='service_type',
            field=models.CharField(choices=[('Cabinet Painting', 'Cabinet Painting'), ('Door Painting', 'Door Painting'), ('Exterior Painting', 'Exterior Painting'), ('Interior Painting', 'Interior Painting'), ('Window Painting', 'Window Painting'), ('Fence Painting', 'Fence Painting')], default='Cabinet Painting', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
