# Generated by Django 5.1.6 on 2025-02-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0003_contactrequest_address_contactrequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
