# Generated by Django 5.1.6 on 2025-03-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0004_service_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_sms',
            field=models.BooleanField(default=True),
        ),
    ]
