# Generated by Django 5.1.6 on 2025-03-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0005_user_allow_sms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
