# Generated by Django 5.1.6 on 2025-03-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0006_alter_contactrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimaterequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
    ]
